name: Python CI/CD Pipeline

on:
  push:
    branches: [ "*" ]  # Triggers on any branch push
  pull_request:
    branches: [ "main" ]  # Triggers on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checks out your repo

    - name: Set up Python
      uses: actions/setup-python@v4  # Correct Python setup
      with:
        python-version: '3.11'  # Use your Python version (3.8, 3.9, etc.)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file
        # If using pytest:
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        python -m pytest  # Runs all tests (adjust if using unittest)

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()  # Uploads even if tests fail
      with:
        name: coverage-report
        path: |
          coverage.xml
          htmlcov/

    - name: Build package (wheel)
      if: github.ref == 'refs/heads/main'  # Only on main branch
      run: |
        python setup.py sdist bdist_wheel  # If using setuptools

    - name: Upload distribution
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main'
      with:
        name: python-package
        path: dist/*
