name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Build wheel and upload artifact
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
      continue-on-error: false

    - name: Upload Artifact
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: bookstore-package
        path: dist/*.whl
