name: Basic CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Basic install
        
    - name: Attempt tests (non-blocking)
      continue-on-error: true  # This makes tests optional
      run: |
        python -m pytest || echo "Tests failed - continuing anyway"
        
    - name: Create dummy artifact
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p dist
        echo "Placeholder for artifacts" > dist/dummy.txt
        
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: dist/*

    
    - name: Run tests (optional)
      continue-on-error: true  # 👈 This lets tests fail without blocking
      run: pytest || echo "Tests failed but continuing"
